version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_reverse_proxy
    ports:
      - "6969:80"
    networks:
      - proxy 
    env_file:
      - ../.env

networks:
  proxy:
    driver: bridge
