version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "6969:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
    env_file:
      - ../.env

networks:
  my_network:
    driver: bridge
