version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: scorm-api-db
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local